name: Build APK and Upload to Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas login --token $EXPO_TOKEN

      - name: Build APK with EAS
        id: eas-build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --non-interactive --profile production --json > build-result.json
          echo "BUILD_URL=$(jq -r '.[0].artifacts.buildUrl' build-result.json)" >> $GITHUB_ENV

      - name: Download APK
        run: |
          curl -L "$BUILD_URL" -o app-release.apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
